### ISSUE TITLE
Edges included when only one node present

### ISSUE THREAD

**Issue by bryfox** [codaco/networkQuery#5]
Currently, an edge is included in filtered output if either of its nodes are present (e.g., from an alterRule). Should the edge be excluded unless both of its nodes are present?

**Comment by jthrilly** [comment]
Yes, I think both nodes should be present as this will give greater ground truth validity to the network data model. I hope I am right that the current behaviour is just an oversight...right now I am struggling to think of a plausible reason for it to behave the other way.

**Comment by bryfox** [comment]
To clarify the description, the case I'm talking about is filtering on nodes.

I expected a network that was filtered down to nodeA would not include an edge linking nodeA to nodeB. Are you saying that a nodeB should *not* be filtered out via an `alterRule` if an edge exists that links it?

**Comment by rebeccamadsen** [comment]
So, does the question of whether to include an edge with one or both nodes present depend on whether you are joining the rules with an AND or an OR or whatever?

I could imagine asking if nodeA is connected to anyone at all, and not caring about nodeB. But I could also see it the other way that you do care about both ends of a connection.

**Comment by bryfox** [comment]
I believe rules are applied the same regardless of join type, so behavior is the same.

Your example sounds like something that would be served by an edgeRule (at least hypothetically), rather than trying to filter the graph for only nodeA?

To make this more concrete, [here's a failing assertion](https://github.com/codaco/networkQuery/pull/6/files#diff-c82615bc196144385ef45806f6bb6c27R57).

**Comment by jthrilly** [comment]
Looking at that assertion helped, thanks.

In a note in the documentation (https://github.com/codaco/Network-Canvas/wiki/Network-Query-Builder) we clarify that an `edgeRule` also filters the node list to avoid creating isolates, but we did not specify that the same should be true for an `alterRule`. That is, an `alterRule` that creates orphaned or partially disconnected edges should also filter out those edges. This is because an edge that is not connected at both ends is a logical impossibility in our data model.

To return to your question then:
- The assertion should indeed pass
- Edges that are orphaned or left with one connected edge by a `alterRule` should be filtered from the network by that rule

**Comment by jthrilly** [comment]
One thing to note is that the above is true for an individual subquery, but that the AND|OR behaviour for multiple rules might result in unintuitive results. Consider the following:

- `filterCloseFriends` is an `alterRule` that targets a node property.
- `filterProfessionalFriends` is an `alterRule` that targets a different node property.

- Query 1: `filterCloseFriends` (1)  AND `filterProfessionalFriends` (2).  This will feed the filtered network that results from (1) into (2). Thus, due to the principle set above above regarding disconnected/orphaned edges, this query can only result in _ maintaining_ or _decreasing_ the number of edges between (1) and (2). 
- Query 2: `filterCloseFriends` (1)  OR `filterProfessionalFriends` (2). This will filter the input network twice (once for (1), and once for (2)), and then combine the output. According to the principle set out above, this could result in edges that would be removed by (1) or (2) individually being reinstated as valid when the complete query is evaluated.

**Comment by jthrilly** [comment]
Discussion this morning with @wwqrd has led to further clarification:

- Individual subqueries should not care about isolated edges, as these will be trimmed before returning the filtered network at the end of the overall query.
- To achieve this, we will add back in all edges to the filtered node list after all subqueries have been run, where the node at both ends of the edge is present.

Steve is implementing this functionality now.

**Comment by jthrilly** [comment]
I have opened #7 to cover changes to the UI that we also identified as being needed. @bryfox - these changes are non-trivial, and might not make it in for the next release. I suggest you proceed with a "broken" UI for the filter construction for now, and assume that the component itself will be updated to work for the requirements of Server.

**Comment by wwqrd** [comment]
Here's the functionality for repairing the network: https://github.com/bryfox/networkQuery/pull/1 I'm not sure about naming or at what point it should be called, so at the moment it's used in the top level:

`repair(and(alterQuery(options)))(network)`

**Comment by bryfox** [comment]
I haven't wrapped my head around all of the implications of this, but I don't think ANDed edge rules would always behave correctly here.

Easier shown than explained; I added [another test](https://github.com/codaco/networkQuery/compare/feature/edge-tidy...edge-tidy-test) which fails on the `filter` version. Would you expect that one to pass?

**Comment by jthrilly** [comment]
Yep, that new test should definitely pass.

**Comment by wwqrd** [comment]
I believe this one is resolved based on the decision to make AND behave intuitively correctly!
